server:
  port: 9988
  servlet:
    context-path: /bt/marketplace/${spring.application.name}
spring:
  application:
    name: cart-management
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: bt_marketplace_cart_mgmt
  graphql:
    schema:
      locations: classpath:graphql/
      fileExtensions: .graphqls, .gqls
      printer:
        enabled: true
    path: /graphql
    graphiql:
      enabled: true
      path : /graphiql
  cloud:
    client:
      hostname: 127.0.0.1
    loadbalancer:
      ribbon:
        enabled: false


eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance-id:${random.value}}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
  version: 0.0.1

cloud:
  aws:
    credentials:
      instanceProfile: false
      useDefaultAwsCredentialsChain: true
    region:
      useDefaultAwsRegionChain: true
      static: ap-south-1
    sqs:
      region: ap-south-1
